<a href="https://colab.research.google.com/github/Kenule-dev/Kenule-dev/blob/main/Tutorial_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
from numpy import random

x1=np.array(([1, 2, 3], [5,5,7], [12, 23, 9])); print(x1)
print(np.linalg.det(x1))

y1=np.random.randint(10, 20, size=(3, 3)); y2=np.random.randint(15, 40, size=(3, 3))
y_total= np.add(y1, y2); print(np.linalg.det(y_total))
print(np.linalg.inv(y_total))

[[ 1  2  3]
 [ 5  5  7]
 [12 23  9]]
126.99999999999987
10840.999999999989
[[ 0.02647357 -0.04658242  0.03864957]
 [ 0.07471635  0.01835624 -0.08255696]
 [-0.09261138  0.03403745  0.05294715]]
